// Dados dos imóveis — usados na página de detalhe (imovel.html)

const IMOVEIS = {
  jardins: {
    slug: "jardins",
    titulo: "Apartamento nos Jardins",
    tipo: "Apartamento",
    negocio: "Venda",
    local: "Jardins, São Paulo",
    endereco: "Rua Augusta, 1200 — Jardins, São Paulo",
    preco: "R$ 1.850.000",
    quartos: 3,
    banheiros: 3,
    area: 120,
    vagas: 2,
    condominio: "R$ 2.800 / mês",
    iptu: "R$ 1.200 / mês",
    imagem: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop",
    imagemAlt: "Apartamento moderno com sala ampla e janelas do chão ao teto",
    descricao:
      "Apartamento refinado em um dos endereços mais desejados de São Paulo. Ambientes integrados, acabamento em madeira nobre e iluminação natural em todos os cômodos. Ideal para quem busca conforto e praticidade no coração dos Jardins.",
    caracteristicas: [
      "Varanda gourmet",
      "Suíte master com closet",
      "Ar-condicionado central",
      "Portaria 24h",
      "Academia e salão de festas",
      "2 elevadores sociais",
    ],
  },

  pinheiros: {
    slug: "pinheiros",
    titulo: "Casa em Alto de Pinheiros",
    tipo: "Casa",
    negocio: "Venda",
    local: "Alto de Pinheiros, São Paulo",
    endereco: "Rua Lisboa, 450 — Alto de Pinheiros, São Paulo",
    preco: "R$ 3.200.000",
    quartos: 4,
    banheiros: 5,
    area: 280,
    vagas: 4,
    condominio: "—",
    iptu: "R$ 2.400 / mês",
    imagem: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop",
    imagemAlt: "Casa contemporânea com piscina e área externa",
    descricao:
      "Residência contemporânea com arquitetura assinada, piscina aquecida e jardim paisagístico. Espaços generosos para família, home office e área de lazer completa. Localização privilegiada, próxima a parques e gastronomia de Alto de Pinheiros.",
    caracteristicas: [
      "Piscina aquecida",
      "Jardim com churrasqueira",
      "Home office",
      "Lavabo social",
      "Depósito e lavanderia",
      "Sistema de alarme",
    ],
  },

  "vila-olimpia": {
    slug: "vila-olimpia",
    titulo: "Studio na Vila Olímpia",
    tipo: "Apartamento",
    negocio: "Locação",
    local: "Vila Olímpia, São Paulo",
    endereco: "Av. Brigadeiro Faria Lima, 3400 — Vila Olímpia, São Paulo",
    preco: "R$ 4.500 / mês",
    quartos: 1,
    banheiros: 1,
    area: 45,
    vagas: 1,
    condominio: "Incluso",
    iptu: "Incluso",
    imagem: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop",
    imagemAlt: "Apartamento compacto e bem iluminado",
    descricao:
      "Studio moderno e funcional no epicentro corporativo da Vila Olímpia. Perfeito para profissionais que valorizam mobilidade, design e proximidade com metrô, shoppings e restaurantes. Mobiliado e pronto para morar.",
    caracteristicas: [
      "Mobiliado completo",
      "Cozinha integrada",
      "Vista para a cidade",
      "Condomínio com coworking",
      "Pet friendly",
      "Contrato mínimo 12 meses",
    ],
  },

  "itaim-bibi": {
    slug: "itaim-bibi",
    titulo: "Cobertura no Itaim Bibi",
    tipo: "Cobertura",
    negocio: "Venda",
    local: "Itaim Bibi, São Paulo",
    endereco: "Rua João Cachoeira, 880 — Itaim Bibi, São Paulo",
    preco: "R$ 5.900.000",
    quartos: 4,
    banheiros: 5,
    area: 320,
    vagas: 3,
    condominio: "R$ 4.200 / mês",
    iptu: "R$ 3.100 / mês",
    imagem: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop",
    imagemAlt: "Cobertura com vista panorâmica da cidade",
    descricao:
      "Cobertura duplex com vista panorâmica de 360° e terraço com piscina privativa. Acabamento premium, automação residencial e 4 suítes. Um dos endereços mais exclusivos do Itaim Bibi, com privacidade e sofisticação incomparáveis.",
    caracteristicas: [
      "Terraço com piscina privativa",
      "Vista panorâmica 360°",
      "Automação residencial",
      "4 suítes",
      "Elevador privativo",
      "4 vagas demarcadas",
    ],
  },
};
